title: KeyConf24
description: Keycloak Community 1-Day-Conference
url: https://keyconf.dev
baseurl: "" # the subpath of your site, e.g. /blog
eventbrite: https://www.eventbrite.de/e/keyconf24-tickets-887467387847
showTicketSale: true

# some default values for Front Matter
defaults:
  -
    scope:
      path: "" # emtpy means all files
      type: posts
    values:
      layout: post

markdown: kramdown

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - README.md
  - .git
  - .sass-cache
  - .jekyll-cache
  - buildspec.yml
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
