version: 0.2
env:
  parameter-store:
    SSHPASS: strato-masterpwd
phases:
  install:
    commands:
      - yum --enablerepo=epel -y install sshpass
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec jekyll build
  post_build:
    commands:
      - 'sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r _site/* n-k.de@ssh.strato.de:/keycloak-dev-day/'
